# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RegattaClient < Formula
  desc ""
  homepage "https://github.com/Tantalor93/regatta-client"
  version "0.5.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Tantalor93/regatta-client/releases/download/v0.5.2/regatta-client_darwin_arm64.tar.gz"
      sha256 "2b30b4aa444249ccc47397cc96ec1c953f3fa697de027462784cb0fc9be403dc"

      def install
        bin.install "regatta-client"
        bash_completion.install "completions/regatta-client.bash" => "_regatta-client"
        zsh_completion.install "completions/regatta-client.zsh" => "_regatta-client"
        man1.install Dir["manpages/*.1"]
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Tantalor93/regatta-client/releases/download/v0.5.2/regatta-client_darwin_amd64.tar.gz"
      sha256 "56a5caac263811efbcba3c568465d61d2a2141cf822bfd60c8764b8c9e0b56b6"

      def install
        bin.install "regatta-client"
        bash_completion.install "completions/regatta-client.bash" => "_regatta-client"
        zsh_completion.install "completions/regatta-client.zsh" => "_regatta-client"
        man1.install Dir["manpages/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Tantalor93/regatta-client/releases/download/v0.5.2/regatta-client_linux_amd64.tar.gz"
      sha256 "0a6fbdbf790f9bc956578a5e969d75f463b61dabed32901ebccc440f81ee1ad1"

      def install
        bin.install "regatta-client"
        bash_completion.install "completions/regatta-client.bash" => "_regatta-client"
        zsh_completion.install "completions/regatta-client.zsh" => "_regatta-client"
        man1.install Dir["manpages/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Tantalor93/regatta-client/releases/download/v0.5.2/regatta-client_linux_arm64.tar.gz"
      sha256 "d39f87dca5b9d7ba24aeb5a33402f151c8bde634da77c7a9681306465d399904"

      def install
        bin.install "regatta-client"
        bash_completion.install "completions/regatta-client.bash" => "_regatta-client"
        zsh_completion.install "completions/regatta-client.zsh" => "_regatta-client"
        man1.install Dir["manpages/*.1"]
      end
    end
  end
end
