# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RegattaClient < Formula
  desc ""
  homepage "https://github.com/Tantalor93/regatta-client"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Tantalor93/regatta-client/releases/download/v0.5.0/regatta-client_darwin_amd64.tar.gz"
      sha256 "edc73486171a122b0c06d7b9c659939ece515bc4e08cb4851973af3f5f1283f4"

      def install
        bin.install "regatta-client"
        bash_completion.install "completions/regatta-client.bash" => "_regatta-client"
        zsh_completion.install "completions/regatta-client.zsh" => "_regatta-client"
        man1.install Dir["manpages/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Tantalor93/regatta-client/releases/download/v0.5.0/regatta-client_darwin_arm64.tar.gz"
      sha256 "69e693f582fc6091f246cd2d3440d5866a3d7a325d8e8b88da3435c5d0f17fb4"

      def install
        bin.install "regatta-client"
        bash_completion.install "completions/regatta-client.bash" => "_regatta-client"
        zsh_completion.install "completions/regatta-client.zsh" => "_regatta-client"
        man1.install Dir["manpages/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Tantalor93/regatta-client/releases/download/v0.5.0/regatta-client_linux_amd64.tar.gz"
      sha256 "7f9bcd006259f5662dc7c9b5e49df606815c80a184be5cd41a9fefe8ec855af5"

      def install
        bin.install "regatta-client"
        bash_completion.install "completions/regatta-client.bash" => "_regatta-client"
        zsh_completion.install "completions/regatta-client.zsh" => "_regatta-client"
        man1.install Dir["manpages/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Tantalor93/regatta-client/releases/download/v0.5.0/regatta-client_linux_arm64.tar.gz"
      sha256 "d21edf2be56749245187b9236379f12f42a9b05e1dc7294d9170f366c9d0f212"

      def install
        bin.install "regatta-client"
        bash_completion.install "completions/regatta-client.bash" => "_regatta-client"
        zsh_completion.install "completions/regatta-client.zsh" => "_regatta-client"
        man1.install Dir["manpages/*.1"]
      end
    end
  end
end
